<?php

namespace Database\Seeders\Admin;

use App\Models\Admin\Bank;
use Illuminate\Database\Seeder;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $banks = array(
            array('slug' => 'brac-bank','bank_name' => 'Brac Bank','desc' => '<p>BRAC Bank is a leading financial institution known for its innovative banking solutions and commitment to fostering economic growth in Bangladesh. With a focus on customer-centric services, technological advancement, and sustainable practices, BRAC Bank serves as a trusted partner for individuals and businesses alike, driving progress and financial inclusion across the nation.</p>','input_fields' => '[{"type":"text","label":"IBAN Number","name":"iban_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Swift Code","name":"swift_code","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Full Name","name":"full_name","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}}]','status' => '1','created_at' => '2024-01-31 11:59:46','updated_at' => '2024-01-31 12:01:20'),
            array('slug' => 'mtb-bank','bank_name' => 'MTB Bank','desc' => '<p>MTB Bank, also known as Mutual Trust Bank, is a premier financial institution renowned for its customer-centric approach and comprehensive banking services in Bangladesh. With a strong emphasis on innovation, integrity, and excellence, MTB Bank provides tailored solutions to meet the diverse needs of individuals, businesses, and institutions. Committed to driving economic development and financial empowerment, MTB Bank stands as a trusted partner, fostering growth and prosperity in the communities it serves.</p>','input_fields' => '[{"type":"text","label":"Account Number","name":"account_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Swift Code","name":"swift_code","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Full Name","name":"full_name","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}}]','status' => '1','created_at' => '2024-01-31 12:01:13','updated_at' => '2024-01-31 12:01:13'),
            array('slug' => 'islami-bank','bank_name' => 'Islami Bank','desc' => '<p>Islami Bank Bangladesh Limited is a pioneering financial institution dedicated to providing Shariah-compliant banking solutions in Bangladesh. As the country\'s first Islamic bank, it operates on the principles of Islamic finance, offering a range of products and services tailored to the needs of customers seeking ethical and interest-free banking. With a focus on promoting financial inclusion and social responsibility, Islami Bank plays a vital role in fostering economic development while adhering to Islamic values and principles.</p>','input_fields' => '[{"type":"text","label":"IBAN Number","name":"iban_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Full Name","name":"full_name","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}}]','status' => '1','created_at' => '2024-01-31 12:02:21','updated_at' => '2024-01-31 12:02:21'),
            array('slug' => 'iccb-bank','bank_name' => 'ICCB Bank','desc' => '<p>ICCB Bank, also known as International Commerce and Commercial Bank, is a dynamic financial institution committed to providing innovative banking solutions and fostering international trade in Bangladesh. With a focus on facilitating global transactions and supporting businesses of all sizes, ICCB Bank offers a comprehensive range of banking products and services tailored to meet the diverse needs of its customers. Known for its reliability, efficiency, and dedication to customer satisfaction, ICCB Bank plays a pivotal role in driving economic growth and facilitating cross-border commerce in the region.</p>','input_fields' => '[{"type":"text","label":"Account Number","name":"account_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Account Name","name":"account_name","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}}]','status' => '1','created_at' => '2024-01-31 12:03:18','updated_at' => '2024-01-31 12:03:18'),
            array('slug' => 'bank-asia','bank_name' => 'Bank Asia','desc' => '<p>Bank Asia is a leading financial institution renowned for its innovative banking solutions and commitment to excellence in Bangladesh. With a customer-centric approach, Bank Asia offers a wide range of banking products and services tailored to meet the diverse needs of individuals, businesses, and institutions. Committed to fostering financial inclusion and sustainable development, Bank Asia leverages advanced technology and strategic partnerships to deliver efficient and reliable banking solutions. With a focus on integrity, transparency, and customer satisfaction, Bank Asia continues to play a vital role in driving economic growth and prosperity in the communities it serves.</p>','input_fields' => '[{"type":"text","label":"Account Number","name":"account_number","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}},{"type":"text","label":"Account Name","name":"account_name","required":true,"validation":{"max":"30","mimes":[],"min":"0","options":[],"required":true}}]','status' => '1','created_at' => '2024-01-31 12:04:23','updated_at' => '2024-01-31 12:04:23')
        );
        Bank::insert($banks);
    }
}
